# Generated by Django 5.2.3 on 2025-08-01 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_site_unit_package_materialutilised_materialissued_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='status',
            field=models.CharField(default='INITIAL', max_length=100),
            preserve_default=False,
        ),
    ]
