# Generated by Django 5.2.3 on 2025-08-01 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_site_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='full',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
