# Generated by Django 5.2.3 on 2025-08-01 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_unit_full'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='name',
            field=models.CharField(default='RDSSLR-1', max_length=50),
            preserve_default=False,
        ),
    ]
