# Generated by Django 5.2.3 on 2025-08-02 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_package_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialDismantled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.material')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.site')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialExisting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.material')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.site')),
            ],
        ),
    ]
