# Generated by Django 5.2.3 on 2025-08-02 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_party_packageworkitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workitem',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.package'),
        ),
    ]
