# Generated by Django 5.2.3 on 2025-08-02 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_workitem_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workitem',
            name='package',
        ),
    ]
