# Generated by Django 5.2.3 on 2025-08-02 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_remove_workitem_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workitem',
            name='rate1',
        ),
        migrations.RemoveField(
            model_name='workitem',
            name='rate2',
        ),
        migrations.RemoveField(
            model_name='workitem',
            name='rate3',
        ),
    ]
