# Generated by Django 5.2.3 on 2025-08-02 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_workgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='workitem',
            name='work_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.workgroup'),
        ),
    ]
