# Generated by Django 5.2.3 on 2025-08-02 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_alter_workitem_work_group'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkGroup',
        ),
    ]
