# Generated by Django 5.2.3 on 2025-08-02 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_delete_workgroup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workitem',
            old_name='work_group',
            new_name='party',
        ),
    ]
