# Generated by Django 5.2.3 on 2025-08-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_rename_work_group_workitem_party'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workitem',
            name='party',
        ),
        migrations.AddField(
            model_name='workitem',
            name='party',
            field=models.ManyToManyField(blank=True, to='projects.party'),
        ),
    ]
