# Generated by Django 5.2.3 on 2025-08-02 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_remove_workitem_party_workitem_party'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workitem',
            old_name='party',
            new_name='parties',
        ),
    ]
