# Generated by Django 5.2.3 on 2025-08-02 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_rename_party_workitem_parties'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workitem',
            name='parties',
        ),
    ]
