# Generated by Django 5.2.3 on 2025-08-02 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_workitem_party'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workitem',
            name='party',
        ),
    ]
