# Generated by Django 5.2.3 on 2025-08-02 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_remove_workitem_party'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkItemGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.party')),
                ('work_items', models.ManyToManyField(to='projects.workitem')),
            ],
        ),
    ]
