# Generated by Django 5.2.3 on 2025-08-02 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_workitemgroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workitemgroup',
            name='work_items',
        ),
    ]
