# Generated by Django 5.2.3 on 2025-08-02 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_remove_workitemgroup_work_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='workitemgroup',
            name='work_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.workitem'),
        ),
    ]
