# Generated by Django 5.2.3 on 2025-08-02 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_workitemgroup_work_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packageworkitem',
            name='rate1',
        ),
        migrations.RemoveField(
            model_name='packageworkitem',
            name='rate2',
        ),
        migrations.RemoveField(
            model_name='packageworkitem',
            name='rate3',
        ),
        migrations.RemoveField(
            model_name='packageworkitem',
            name='work_item',
        ),
        migrations.AddField(
            model_name='workitemgroup',
            name='rate',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
