# Generated by Django 5.2.3 on 2025-08-02 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_remove_packageworkitem_rate1_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PackageWorkItem',
            new_name='PackageWorkItemGroup',
        ),
    ]
