# Generated by Django 5.2.3 on 2025-08-02 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_rename_packageworkitem_packageworkitemgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageworkitemgroup',
            name='work_item_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.workitemgroup'),
        ),
    ]
