# Generated by Django 5.2.3 on 2025-08-02 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_packageworkitemgroup_work_item_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project'),
        ),
    ]
