# Generated by Django 5.2.3 on 2025-08-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_package_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialboq',
            name='quantity_issued',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='materialboq',
            name='quantity_utilised',
            field=models.FloatField(default=0),
        ),
    ]
