# Generated by Django 5.2.3 on 2025-08-02 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_materialboq_quantity_issued_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialutilised',
            name='material',
        ),
        migrations.RemoveField(
            model_name='materialutilised',
            name='site',
        ),
        migrations.RemoveField(
            model_name='workexecuted',
            name='material_utilised',
        ),
        migrations.DeleteModel(
            name='MaterialIssued',
        ),
        migrations.DeleteModel(
            name='MaterialUtilised',
        ),
    ]
