# Generated by Django 5.2.3 on 2025-08-02 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0031_person_workitem_ref_material_estimation_cashflow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workitem',
            name='ref_material',
        ),
    ]
