# Generated by Django 5.2.3 on 2025-08-02 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0032_remove_workitem_ref_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='workitem',
            name='ref_material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.material'),
        ),
    ]
