# Generated by Django 5.2.3 on 2025-08-02 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0033_workitem_ref_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimation',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.package'),
        ),
    ]
