# Generated by Django 5.2.3 on 2025-08-02 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0034_estimation_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimation',
            name='pwig',
        ),
    ]
