# Generated by Django 5.2.3 on 2025-08-02 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0035_remove_estimation_pwig'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PackageWorkItemGroup',
        ),
    ]
