# Generated by Django 5.2.3 on 2025-08-02 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0036_delete_packageworkitemgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='workitemgroup',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.package'),
        ),
    ]
