# Generated by Django 5.2.3 on 2025-08-02 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0037_workitemgroup_package'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('rate', models.FloatField()),
                ('work_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.workitem')),
            ],
        ),
    ]
