# Generated by Django 5.2.3 on 2025-08-02 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0038_ratemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratemodel',
            name='work_items',
            field=models.ManyToManyField(related_name='work_items', to='projects.workitem'),
        ),
    ]
