# Generated by Django 5.2.3 on 2025-08-02 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0039_ratemodel_work_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratemodel',
            name='work_items',
        ),
    ]
