# Generated by Django 5.2.3 on 2025-08-02 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0040_remove_ratemodel_work_items'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RateModel',
            new_name='ItemRate',
        ),
    ]
