# Generated by Django 5.2.3 on 2025-08-02 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0041_rename_ratemodel_itemrate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemrate',
            name='name',
        ),
        migrations.CreateModel(
            name='ItemRateGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('item_rates', models.ManyToManyField(to='projects.itemrate')),
            ],
        ),
    ]
