# Generated by Django 5.2.3 on 2025-08-02 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0042_remove_itemrate_name_itemrategroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemrate',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
