# Generated by Django 5.2.3 on 2025-08-02 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0044_itemrate_party'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemrate',
            name='name',
        ),
    ]
