# Generated by Django 5.2.3 on 2025-08-02 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0045_remove_itemrate_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workitemgroup',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='workitemgroup',
            name='work_item',
        ),
    ]
