# Generated by Django 5.2.3 on 2025-08-02 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0047_workitemgroup_item_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemrategroup',
            name='party',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.party'),
        ),
    ]
