# Generated by Django 5.2.3 on 2025-08-02 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0048_itemrategroup_party'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workitemgroup',
            name='item_group',
        ),
        migrations.DeleteModel(
            name='ItemRateGroup',
        ),
    ]
