# Generated by Django 5.2.3 on 2025-08-02 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0049_remove_workitemgroup_item_group_delete_itemrategroup'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorkItemGroup',
            new_name='WorkGroup',
        ),
    ]
