# Generated by Django 5.2.3 on 2025-08-02 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0050_rename_workitemgroup_workgroup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Estimation',
        ),
    ]
