# Generated by Django 5.2.3 on 2025-08-02 20:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0051_delete_estimation'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('remark', models.TextField(blank=True)),
                ('work_executed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.workexecuted')),
            ],
        ),
    ]
