# Generated by Django 5.2.3 on 2025-08-02 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0053_person_party'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.party'),
        ),
    ]
