# Generated by Django 5.2.3 on 2025-08-02 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0054_alter_person_party'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflow',
            name='payee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payee', to='projects.person'),
        ),
    ]
