# Generated by Django 5.2.3 on 2025-08-02 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0055_alter_cashflow_payee'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemrate',
            name='settled',
            field=models.BooleanField(default=False),
        ),
    ]
