# Generated by Django 5.2.3 on 2025-08-02 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0056_itemrate_settled'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflow',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.package'),
        ),
    ]
