# Generated by Django 5.2.3 on 2025-08-03 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0057_cashflow_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexecuted',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.site', verbose_name='site'),
        ),
    ]
