# Generated by Django 5.2.3 on 2025-08-03 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0058_alter_workexecuted_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflow',
            name='include',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cashflow',
            name='virtual',
            field=models.BooleanField(default=False),
        ),
    ]
