# Generated by Django 5.2.3 on 2025-08-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0059_cashflow_include_cashflow_virtual'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workprogress',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='workitem',
            name='index',
            field=models.BooleanField(default=False),
        ),
    ]
