# Generated by Django 5.2.3 on 2025-08-06 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0060_alter_workprogress_options_workitem_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='workprogress',
            name='quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='workprogress',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.site', verbose_name='site'),
        ),
        migrations.AddField(
            model_name='workprogress',
            name='work_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.workitem'),
        ),
    ]
