# Generated by Django 5.2.3 on 2025-08-06 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0061_workprogress_quantity_workprogress_site_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workprogress',
            name='work_executed',
        ),
    ]
