# Generated by Django 5.2.3 on 2025-08-06 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0062_remove_workprogress_work_executed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkExecuted',
        ),
    ]
