# Generated by Django 5.2.3 on 2025-08-06 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0063_delete_workexecuted'),
    ]

    operations = [
        migrations.AddField(
            model_name='workprogress',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
