# Generated by Django 5.2.3 on 2025-08-08 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0064_workprogress_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workprogress',
            name='remark',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
