# Generated by Django 5.2.3 on 2025-08-15 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0065_alter_workprogress_remark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workitem',
            name='unit',
        ),
    ]
