# Generated by Django 5.2.3 on 2025-08-15 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0066_remove_workitem_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialexisting',
            name='material',
        ),
        migrations.RemoveField(
            model_name='materialexisting',
            name='site',
        ),
        migrations.DeleteModel(
            name='MaterialDismantled',
        ),
        migrations.DeleteModel(
            name='MaterialExisting',
        ),
    ]
