# Generated by Django 5.2.3 on 2025-07-23 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feeder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feeder_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=20)),
                ('substation', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DTR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtr_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('capacity_kva', models.IntegerField()),
                ('location', models.CharField(blank=True, max_length=12, null=True)),
                ('feeder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infrastructure.feeder')),
            ],
        ),
    ]
