# Generated by Django 5.2.3 on 2025-07-26 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dtr',
            name='dtr_id',
            field=models.CharField(max_length=20),
        ),
    ]
