# Generated by Django 5.2.3 on 2025-07-26 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0002_alter_dtr_dtr_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeder',
            name='feeder_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='feeder',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='feeder',
            name='substation',
            field=models.CharField(max_length=50),
        ),
    ]
