# Generated by Django 5.2.3 on 2025-07-26 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0003_alter_feeder_feeder_id_alter_feeder_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dtr',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
