# Generated by Django 5.2.3 on 2025-07-26 17:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('text', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('OK', 'OK'), ('PENDING', 'PENDING'), ('FAILED', 'FAILED'), ('--', '--')], default='--', max_length=50)),
                ('status_text', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('subject', models.CharField(max_length=100)),
                ('info', models.TextField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OK', 'OK'), ('PENDING', 'PENDING'), ('FAILED', 'FAILED')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WorkProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office.progress')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office.work')),
            ],
        ),
    ]
