# Generated by Django 5.2.3 on 2025-07-26 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='status',
            field=models.CharField(choices=[('OK', 'OK'), ('PENDING', 'PENDING'), ('ONGOING', 'ONGOING'), ('FAILED', 'FAILED'), ('--', '--')], default='--', max_length=50),
        ),
        migrations.AlterField(
            model_name='work',
            name='status',
            field=models.CharField(choices=[('OK', 'OK'), ('PENDING', 'PENDING'), ('ONGOING', 'ONGOING'), ('FAILED', 'FAILED')], max_length=50),
        ),
    ]
