# Generated by Django 5.2.3 on 2025-07-27 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0002_alter_progress_status_alter_work_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='subject',
            field=models.TextField(),
        ),
    ]
