# Generated by Django 5.2.3 on 2025-07-28 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0003_alter_work_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='priority',
            field=models.CharField(choices=[('LOW', 'LOW'), ('MEDIUM', 'MEDIUM'), ('HIGH', 'HIGH')], default='LOW'),
        ),
    ]
