# Generated by Django 5.2.3 on 2025-07-29 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0004_work_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='status',
            field=models.CharField(choices=[('OK', 'OK'), ('PENDING', 'PENDING'), ('ONGOING', 'ONGOING'), ('FAILED', 'FAILED')], default='PENDING', max_length=50),
        ),
    ]
