# Generated by Django 5.2.3 on 2025-08-08 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0005_alter_work_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='status',
            field=models.CharField(choices=[('DONE', 'DONE'), ('PENDING', 'PENDING'), ('ONGOING', 'ONGOING'), ('FAILED', 'FAILED'), ('--', '--')], default='--', max_length=50),
        ),
        migrations.AlterField(
            model_name='work',
            name='status',
            field=models.CharField(choices=[('DONE', 'DONE'), ('PENDING', 'PENDING'), ('ONGOING', 'ONGOING'), ('FAILED', 'FAILED')], default='PENDING', max_length=50),
        ),
    ]
