# Generated by Django 5.2.3 on 2025-08-09 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0006_alter_progress_status_alter_work_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='priority',
            field=models.CharField(choices=[('LOW', 'LOW'), ('MEDIUM', 'MEDIUM'), ('HIGH', 'HIGH')], default='LOW', max_length=20),
        ),
    ]
