# Generated by Django 5.2.3 on 2025-07-12 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raid',
            name='cash_flows',
            field=models.ManyToManyField(blank=True, to='consumers.cashflow'),
        ),
    ]
