# Generated by Django 5.2.3 on 2025-07-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumerhistory',
            name='remark',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='unauthconsumer',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
