# Generated by Django 5.2.3 on 2025-07-12 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0002_alter_raid_cash_flows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raid',
            name='action',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='raid',
            name='info',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='raid',
            name='observation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
