# Generated by Django 5.2.3 on 2025-07-05 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0002_alter_consumerhistory_remark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='raid',
            name='unused',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='consumerhistory',
            name='remark',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='unauthconsumer',
            name='remark',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
