# Generated by Django 5.2.3 on 2025-07-12 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0003_alter_raid_action_alter_raid_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='raid',
            name='penalty_paid',
            field=models.BooleanField(default=False),
        ),
    ]
