# Generated by Django 5.2.3 on 2025-07-05 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0003_raid_unused_alter_consumerhistory_remark_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raid',
            name='info',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='raid',
            name='observation',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
