# Generated by Django 5.2.3 on 2025-07-13 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0004_raid_penalty_paid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consumerhistory',
            old_name='cash_flow',
            new_name='cash_flows',
        ),
    ]
