# Generated by Django 5.2.3 on 2025-07-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0004_alter_raid_info_alter_raid_observation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumerhistory',
            name='remark',
            field=models.TextField(max_length=500),
        ),
    ]
