# Generated by Django 5.2.3 on 2025-07-13 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0005_rename_cash_flow_consumerhistory_cash_flows'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=20)),
                ('value', models.CharField(max_length=30)),
                ('consumer', models.ManyToManyField(to='consumers.consumer')),
            ],
        ),
    ]
