# Generated by Django 5.2.3 on 2025-07-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0005_alter_consumerhistory_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumerhistory',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('HOLD', 'HOLD'), ('', '')], default=''),
        ),
        migrations.AddField(
            model_name='consumerhistory',
            name='status_justification',
            field=models.TextField(blank=True, null=True),
        ),
    ]
