# Generated by Django 5.2.3 on 2025-07-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0006_consumerhistory_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='phase',
            field=models.CharField(choices=[('SINGLE', 'SINGLE'), ('THREE', 'THREE')], max_length=10),
        ),
    ]
