# Generated by Django 5.2.3 on 2025-07-13 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0006_consumerinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consumerinfo',
            old_name='consumer',
            new_name='consumers',
        ),
    ]
