# Generated by Django 5.2.3 on 2025-07-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0007_alter_consumer_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='bill_upto',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consumer',
            name='current_outstanding',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
