# Generated by Django 5.2.3 on 2025-07-13 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0007_rename_consumer_consumerinfo_consumers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumerinfo',
            name='consumers',
            field=models.ManyToManyField(blank=True, to='consumers.consumer'),
        ),
    ]
