# Generated by Django 5.2.3 on 2025-07-06 16:52

import location_field.models.plain
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0008_consumer_bill_upto_consumer_current_outstanding'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='location',
            field=location_field.models.plain.PlainLocationField(blank=True, max_length=63),
        ),
    ]
