# Generated by Django 5.2.3 on 2025-07-13 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0008_alter_consumerinfo_consumers'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumerExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(blank=True, max_length=30, null=True)),
                ('consumer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='consumers.consumer')),
            ],
        ),
    ]
