# Generated by Django 5.2.3 on 2025-07-13 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0009_consumerextension'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='infos',
            field=models.ManyToManyField(blank=True, to='consumers.consumerinfo'),
        ),
    ]
