# Generated by Django 5.2.3 on 2025-07-06 17:15

import location_field.models.plain
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0009_consumer_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='location',
            field=location_field.models.plain.PlainLocationField(default='24.823044419753995,93.95751714635482', max_length=63),
        ),
    ]
