# Generated by Django 5.2.3 on 2025-07-09 06:33

import location_field.models.plain
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0010_alter_consumer_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumer',
            name='latlong',
        ),
        migrations.AlterField(
            model_name='consumer',
            name='location',
            field=location_field.models.plain.PlainLocationField(blank=True, default='24.823044419753995,93.95751714635482', max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='consumerhistory',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDING', 'PENDING'), ('HOLD', 'HOLD'), ('COMPLETED', 'COMPLETED'), ('', '')], default=''),
        ),
    ]
