# Generated by Django 5.2.3 on 2025-07-14 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0010_consumer_infos'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumerhistory',
            name='none',
            field=models.BooleanField(default=False),
        ),
    ]
