# Generated by Django 5.2.3 on 2025-07-14 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0011_consumerhistory_none'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumerhistory',
            name='none',
        ),
        migrations.AddField(
            model_name='raid',
            name='none',
            field=models.BooleanField(default=False),
        ),
    ]
