# Generated by Django 5.2.3 on 2025-07-09 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0011_remove_consumer_latlong_alter_consumer_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='raid',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
