# Generated by Django 5.2.3 on 2025-07-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0012_raid_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raid',
            name='action',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
