# Generated by Django 5.2.3 on 2025-07-14 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0012_remove_consumerhistory_none_raid_none'),
    ]

    operations = [
        migrations.RenameField(
            model_name='raid',
            old_name='none',
            new_name='ok',
        ),
        migrations.AddField(
            model_name='raid',
            name='unused',
            field=models.BooleanField(default=False),
        ),
    ]
