# Generated by Django 5.2.3 on 2025-07-14 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0013_rename_none_raid_ok_raid_unused'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_staff', models.BooleanField(default=True)),
                ('contact_nos', models.CharField(max_length=50)),
                ('lead', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='raid',
            name='unauth',
        ),
        migrations.AddField(
            model_name='raid',
            name='underbilled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unauthconsumer',
            name='loads',
            field=models.ManyToManyField(blank=True, to='consumers.loadsurvey'),
        ),
        migrations.AddField(
            model_name='unauthconsumer',
            name='purpose',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='unauthconsumer',
            name='connected_by',
            field=models.ManyToManyField(blank=True, to='consumers.staff'),
        ),
    ]
