# Generated by Django 5.2.3 on 2025-07-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0014_staff_remove_raid_unauth_raid_underbilled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unauthconsumer',
            name='followup',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='unauthconsumer',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unauthconsumer',
            name='resolution',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='StaffAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment', models.CharField(max_length=100)),
                ('staffs', models.ManyToManyField(to='consumers.staff')),
            ],
        ),
        migrations.AddField(
            model_name='unauthconsumer',
            name='staffs_assignments',
            field=models.ManyToManyField(blank=True, to='consumers.staffassignment'),
        ),
    ]
