# Generated by Django 5.2.3 on 2025-07-14 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0015_unauthconsumer_followup_unauthconsumer_is_closed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='raid',
            name='unauth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consumers.unauthconsumer'),
        ),
    ]
