# Generated by Django 5.2.3 on 2025-07-14 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0016_raid_unauth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raid',
            name='unauth',
        ),
    ]
