# Generated by Django 5.2.3 on 2025-07-14 16:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0017_remove_raid_unauth'),
    ]

    operations = [
        migrations.AddField(
            model_name='unauthconsumer',
            name='report_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
