# Generated by Django 5.2.3 on 2025-07-14 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0018_unauthconsumer_report_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflow',
            name='office',
            field=models.BooleanField(default=False),
        ),
    ]
