# Generated by Django 5.2.3 on 2025-07-14 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0019_cashflow_office'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raid',
            name='cash_flows',
        ),
    ]
