# Generated by Django 5.2.3 on 2025-07-14 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0020_remove_raid_cash_flows'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumerhistory',
            name='cash_flows',
        ),
    ]
