# Generated by Django 5.2.3 on 2025-07-14 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0021_remove_consumerhistory_cash_flows'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflow',
            name='chistory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='consumers.consumerhistory'),
        ),
        migrations.AddField(
            model_name='cashflow',
            name='raid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='consumers.raid'),
        ),
    ]
