# Generated by Django 5.2.3 on 2025-07-14 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0022_cashflow_chistory_cashflow_raid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashflow',
            old_name='office',
            new_name='revenue',
        ),
    ]
