# Generated by Django 5.2.3 on 2025-07-16 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0023_rename_office_cashflow_revenue'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=30)),
                ('group_activated', models.BooleanField(default=False)),
            ],
        ),
    ]
