# Generated by Django 5.2.3 on 2025-07-16 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0025_consumerselection'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumergroup',
            name='consumer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consumers.consumer'),
        ),
        migrations.DeleteModel(
            name='ConsumerSelection',
        ),
    ]
