# Generated by Django 5.2.3 on 2025-07-16 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0026_consumergroup_consumer_delete_consumerselection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumergroup',
            name='consumer',
        ),
        migrations.AddField(
            model_name='consumergroup',
            name='consumer',
            field=models.ManyToManyField(blank=True, to='consumers.consumer'),
        ),
    ]
