# Generated by Django 5.2.3 on 2025-07-17 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0027_remove_consumergroup_consumer_consumergroup_consumer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumergroup',
            name='group_activated',
        ),
    ]
