# Generated by Django 5.2.3 on 2025-07-17 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0028_remove_consumergroup_group_activated'),
    ]

    operations = [
        migrations.CreateModel(
            name='RechargeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_id', models.CharField(max_length=20)),
                ('meter_no', models.CharField(max_length=10)),
                ('meter_make', models.IntegerField()),
                ('consumer_name', models.CharField(max_length=50)),
                ('amount', models.FloatField()),
                ('paid_on', models.DateField()),
                ('pay_mode', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
