# Generated by Django 5.2.3 on 2025-07-17 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0029_rechargehistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumergroup',
            name='id',
        ),
        migrations.AddField(
            model_name='consumergroup',
            name='group_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
