# Generated by Django 5.2.3 on 2025-07-17 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0030_remove_consumergroup_id_consumergroup_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumergroup',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='consumergroup',
            name='group_id',
            field=models.IntegerField(default=0),
        ),
    ]
