# Generated by Django 5.2.3 on 2025-07-17 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0031_consumergroup_id_alter_consumergroup_group_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumergroup',
            name='group_id',
        ),
    ]
