# Generated by Django 5.2.3 on 2025-07-17 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0033_consumergroup_group_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumergroup',
            name='group_id',
        ),
        migrations.AddField(
            model_name='consumergroup',
            name='group_code',
            field=models.IntegerField(default=0),
        ),
    ]
