# Generated by Django 5.2.3 on 2025-07-17 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0034_remove_consumergroup_group_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConsumerGroup',
        ),
    ]
