# Generated by Django 5.2.3 on 2025-07-17 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0035_delete_consumergroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_code', models.IntegerField(default=0)),
                ('group_name', models.CharField(max_length=30)),
                ('consumer', models.ManyToManyField(blank=True, to='consumers.consumer')),
            ],
        ),
    ]
