# Generated by Django 5.2.3 on 2025-07-17 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0036_consumergroup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consumergroup',
            old_name='group_code',
            new_name='group_id',
        ),
    ]
