# Generated by Django 5.2.3 on 2025-07-17 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0037_rename_group_code_consumergroup_group_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumergroup',
            name='id',
        ),
        migrations.AlterField(
            model_name='consumergroup',
            name='group_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
