# Generated by Django 5.2.3 on 2025-07-17 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0038_remove_consumergroup_id_alter_consumergroup_group_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consumergroup',
            old_name='group_id',
            new_name='id',
        ),
    ]
