# Generated by Django 5.2.3 on 2025-07-17 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0039_rename_group_id_consumergroup_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumergroup',
            name='group_id',
            field=models.IntegerField(default=0),
        ),
    ]
