# Generated by Django 5.2.3 on 2025-07-17 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0041_alter_consumergroup_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumergroup',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
