# Generated by Django 5.2.3 on 2025-07-17 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0042_alter_consumergroup_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumergroup',
            name='group_id',
        ),
    ]
