# Generated by Django 5.2.3 on 2025-07-17 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0043_remove_consumergroup_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumergroup',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
