# Generated by Django 5.2.3 on 2025-07-18 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0044_alter_consumergroup_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='contact_nos',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
