# Generated by Django 5.2.3 on 2025-07-18 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0045_alter_staff_contact_nos'),
    ]

    operations = [
        migrations.AddField(
            model_name='raid',
            name='unauth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consumers.unauthconsumer'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='lead',
            field=models.BooleanField(default=False),
        ),
    ]
