# Generated by Django 5.2.3 on 2025-07-18 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0046_raid_unauth_alter_staff_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='raid',
            name='staffs_assignments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consumers.staffassignment'),
        ),
        migrations.AddField(
            model_name='raid',
            name='unauthorised',
            field=models.BooleanField(default=False),
        ),
    ]
