# Generated by Django 5.2.3 on 2025-07-21 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0047_raid_staffs_assignments_raid_unauthorised'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_class', models.CharField(choices=[('LT', 'LT'), ('HT', 'HT')], default='LT')),
                ('category', models.CharField(choices=[('Domestic', 'Domestic'), ('Commercial', 'Commercial'), ('Small Industry', 'Small Industry'), ('Public Lighting', 'Public Lighting')], default='Domestic')),
                ('year', models.IntegerField(default=2025)),
                ('demand_charge', models.FloatField()),
                ('rate1', models.FloatField()),
                ('rate2', models.FloatField()),
                ('rate3', models.FloatField()),
                ('load_factor', models.FloatField()),
                ('demand_factor', models.FloatField()),
                ('late_surcharge', models.FloatField()),
            ],
        ),
    ]
