# Generated by Django 5.2.3 on 2025-07-21 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0048_tariff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='energyassessment',
            name='demand_factor',
        ),
        migrations.RemoveField(
            model_name='energyassessment',
            name='fixed_charge',
        ),
        migrations.RemoveField(
            model_name='energyassessment',
            name='load_factor',
        ),
        migrations.RemoveField(
            model_name='energyassessment',
            name='penalty_factor',
        ),
        migrations.RemoveField(
            model_name='energyassessment',
            name='rate',
        ),
        migrations.AddField(
            model_name='energyassessment',
            name='tariff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='consumers.tariff'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='demand_factor',
            field=models.FloatField(default=0.45),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='late_surcharge',
            field=models.FloatField(default=2),
        ),
    ]
