# Generated by Django 5.2.3 on 2025-07-21 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0049_remove_energyassessment_demand_factor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='energyassessment',
            name='demand_factor',
            field=models.FloatField(default=0.45),
        ),
        migrations.AddField(
            model_name='energyassessment',
            name='fixed_charge',
            field=models.FloatField(default=65),
        ),
        migrations.AddField(
            model_name='energyassessment',
            name='load_factor',
            field=models.FloatField(default=0.4),
        ),
        migrations.AddField(
            model_name='energyassessment',
            name='penalty_factor',
            field=models.FloatField(default=3.0),
        ),
        migrations.AddField(
            model_name='energyassessment',
            name='rate',
            field=models.FloatField(default=5.1),
        ),
    ]
