# Generated by Django 5.2.3 on 2025-07-21 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0050_energyassessment_demand_factor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='energyassessment',
            name='demand_factor',
        ),
        migrations.RemoveField(
            model_name='energyassessment',
            name='fixed_charge',
        ),
        migrations.RemoveField(
            model_name='energyassessment',
            name='load_factor',
        ),
        migrations.RemoveField(
            model_name='energyassessment',
            name='penalty_factor',
        ),
        migrations.RemoveField(
            model_name='energyassessment',
            name='rate',
        ),
    ]
