# Generated by Django 5.2.3 on 2025-07-21 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0051_remove_energyassessment_demand_factor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='energyassessment',
            name='tariff',
        ),
    ]
