# Generated by Django 5.2.3 on 2025-07-21 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0052_remove_energyassessment_tariff'),
    ]

    operations = [
        migrations.AddField(
            model_name='energyassessment',
            name='tariff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='consumers.tariff'),
        ),
    ]
