# Generated by Django 5.2.3 on 2025-07-21 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0053_energyassessment_tariff'),
    ]

    operations = [
        migrations.AddField(
            model_name='energyassessment',
            name='penalty_factor',
            field=models.FloatField(default=3.0),
        ),
    ]
