# Generated by Django 5.2.3 on 2025-07-21 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0054_energyassessment_penalty_factor'),
    ]

    operations = [
        migrations.AddField(
            model_name='energyassessment',
            name='mf_full',
            field=models.BooleanField(default=False),
        ),
    ]
