# Generated by Django 5.2.3 on 2025-07-22 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0055_energyassessment_mf_full'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solarconsumer',
            name='capacity_kw',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solarconsumer',
            name='net_meter_no',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='solarconsumer',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
