# Generated by Django 5.2.3 on 2025-07-23 10:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0056_alter_solarconsumer_capacity_kw_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('contact_nos', models.CharField(blank=True, max_length=30, null=True)),
                ('purpose', models.CharField(blank=True, max_length=100, null=True)),
                ('remark', models.CharField(blank=True, max_length=100, null=True)),
                ('followup', models.CharField(blank=True, max_length=100, null=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('authorised_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorised_by', to='consumers.staff')),
                ('cash_flows', models.ManyToManyField(blank=True, to='consumers.cashflow')),
                ('connected_by', models.ManyToManyField(blank=True, related_name='connected_by', to='consumers.staff')),
                ('energy_assessments', models.ManyToManyField(blank=True, to='consumers.energyassessment')),
                ('loads', models.ManyToManyField(blank=True, to='consumers.loadsurvey')),
            ],
        ),
    ]
