# Generated by Django 5.2.3 on 2025-07-24 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0057_temporaryconnection'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content', models.TextField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('DONE', 'DONE'), ('HOLD', 'HOLD'), ('SKIP', 'SKIP')], default='PENDING', max_length=10)),
                ('remark', models.TextField(blank=True, max_length=200, null=True)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
        ),
    ]
