# Generated by Django 5.2.3 on 2025-07-25 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0058_todo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashflow',
            name='chistory',
        ),
        migrations.RemoveField(
            model_name='cashflow',
            name='raid',
        ),
    ]
