# Generated by Django 5.2.3 on 2025-07-25 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0059_remove_cashflow_chistory_remove_cashflow_raid'),
    ]

    operations = [
        migrations.AddField(
            model_name='raid',
            name='cash_flows',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='consumers.cashflow'),
        ),
    ]
