# Generated by Django 5.2.3 on 2025-07-25 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0060_raid_cash_flows'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumerhistory',
            name='cash_flows',
            field=models.ManyToManyField(blank=True, to='consumers.cashflow'),
        ),
    ]
