# Generated by Django 5.2.3 on 2025-07-25 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0061_consumerhistory_cash_flows'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raid',
            name='cash_flows',
        ),
    ]
