# Generated by Django 5.2.3 on 2025-07-25 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0064_remove_raid_cash_flows_raid_cash_flow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='raid',
            old_name='cash_flow',
            new_name='cash_flows',
        ),
    ]
