# Generated by Django 5.2.3 on 2025-07-25 09:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0065_rename_cash_flow_raid_cash_flows'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField(default=django.utils.timezone.now)),
                ('picked_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('reason', models.CharField(max_length=100)),
                ('action_text', models.CharField(blank=True, max_length=100, null=True)),
                ('new_meter', models.CharField(blank=True, max_length=10, null=True)),
                ('action_date', models.DateField(blank=True, null=True)),
                ('remark', models.CharField(blank=True, max_length=100, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('consumer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='consumers.consumer')),
                ('custody', models.ManyToManyField(related_name='custody', to='consumers.staff')),
                ('installed_by', models.ManyToManyField(related_name='installed_by', to='consumers.staff')),
                ('picked_by', models.ManyToManyField(related_name='picked_by', to='consumers.staff')),
            ],
        ),
    ]
