# Generated by Django 5.2.3 on 2025-07-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0066_meter'),
    ]

    operations = [
        migrations.AddField(
            model_name='meter',
            name='prioritized',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='meter',
            name='installed_by',
            field=models.ManyToManyField(blank=True, related_name='installed_by', to='consumers.staff'),
        ),
    ]
