# Generated by Django 5.2.3 on 2025-07-25 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0067_meter_prioritized_alter_meter_installed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='meter',
            name='postpaid',
            field=models.BooleanField(default=False),
        ),
    ]
