# Generated by Django 5.2.3 on 2025-07-25 10:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0068_meter_postpaid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('complaint', models.TextField()),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('remark', models.CharField(blank=True, max_length=100, null=True)),
                ('consumer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='consumers.consumer')),
            ],
        ),
    ]
