# Generated by Django 5.2.3 on 2025-07-25 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0069_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='action',
            field=models.TextField(blank=True, null=True),
        ),
    ]
