# Generated by Django 5.2.3 on 2025-07-25 11:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0070_complaint_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('text', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='complaint',
            name='logs',
            field=models.ManyToManyField(blank=True, to='consumers.log'),
        ),
    ]
