# Generated by Django 5.2.3 on 2025-07-25 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0071_log_complaint_logs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='logs',
        ),
    ]
