# Generated by Django 5.2.3 on 2025-07-25 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0072_remove_complaint_logs'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consumers.complaint')),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consumers.log')),
            ],
        ),
    ]
