# Generated by Django 5.2.3 on 2025-07-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0073_complaintlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintlog',
            name='awaiting',
            field=models.BooleanField(default=False),
        ),
    ]
