# Generated by Django 5.2.3 on 2025-07-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0075_remove_complaintlog_awaiting_log_awaiting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='awaiting',
        ),
        migrations.AddField(
            model_name='complaintlog',
            name='awaiting',
            field=models.BooleanField(default=False),
        ),
    ]
