# Generated by Django 5.2.3 on 2025-07-25 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0077_remove_complaintlog_awaiting_log_awaiting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='text',
            new_name='text1',
        ),
    ]
