# Generated by Django 5.2.3 on 2025-07-25 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0078_rename_text_log_text1'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='text2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
