# Generated by Django 5.2.3 on 2025-07-26 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0079_log_text2'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='connection_status',
            field=models.CharField(default='ACTIVE'),
        ),
    ]
