# Generated by Django 5.2.3 on 2025-07-26 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0080_consumer_connection_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consumers.consumerhistory')),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consumers.log')),
            ],
        ),
    ]
