# Generated by Django 5.2.3 on 2025-07-26 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0081_historylog'),
        ('office', '0002_alter_progress_status_alter_work_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consumers.consumerhistory')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office.work')),
            ],
        ),
    ]
