# Generated by Django 5.2.3 on 2025-07-27 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0082_historywork'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumerhistory',
            name='meter_defective',
        ),
        migrations.RemoveField(
            model_name='consumerhistory',
            name='meter_replaced',
        ),
        migrations.RemoveField(
            model_name='consumerhistory',
            name='status',
        ),
        migrations.RemoveField(
            model_name='consumerhistory',
            name='status_justification',
        ),
        migrations.RemoveField(
            model_name='consumerhistory',
            name='summoned',
        ),
    ]
