# Generated by Django 5.2.3 on 2025-07-27 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0083_remove_consumerhistory_meter_defective_and_more'),
        ('office', '0002_alter_progress_status_alter_work_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumerWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consumers.consumer')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office.work')),
            ],
        ),
    ]
