# Generated by Django 5.2.3 on 2025-07-27 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0084_consumerwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='subdivision',
            field=models.CharField(default='smg', max_length=20),
        ),
    ]
