# Generated by Django 5.2.3 on 2025-07-27 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0085_consumer_subdivision'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaidGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('raids', models.ManyToManyField(to='consumers.raid')),
            ],
        ),
    ]
