# Generated by Django 5.2.3 on 2025-07-27 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0086_raidgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raid',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='raid',
            name='observation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='raidgroup',
            name='raids',
            field=models.ManyToManyField(blank=True, to='consumers.raid'),
        ),
    ]
