# Generated by Django 5.2.3 on 2025-07-27 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0087_alter_raid_info_alter_raid_observation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumerhistory',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
