# Generated by Django 5.2.3 on 2025-07-28 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0088_alter_consumerhistory_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='meter',
            name='balance',
            field=models.FloatField(default=0),
        ),
    ]
