# Generated by Django 5.2.3 on 2025-07-28 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0089_meter_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleConsumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_name', models.CharField(max_length=100)),
                ('consumer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='consumers.consumer')),
                ('consumers', models.ManyToManyField(blank=True, related_name='close_consumers', to='consumers.consumer')),
            ],
        ),
    ]
