# Generated by Django 5.2.3 on 2025-07-28 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0090_multipleconsumer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MultipleConsumer',
            new_name='MultiConsumer',
        ),
    ]
