# Generated by Django 5.2.3 on 2025-07-28 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0091_rename_multipleconsumer_multiconsumer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multiconsumer',
            name='relationship_name',
        ),
    ]
