# Generated by Django 5.2.3 on 2025-07-28 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0092_remove_multiconsumer_relationship_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiconsumer',
            name='remark',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='multiconsumer',
            name='consumer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='consumers.consumer'),
        ),
    ]
