# Generated by Django 5.2.3 on 2025-07-29 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0093_multiconsumer_remark_alter_multiconsumer_consumer'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiconsumer',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
