# Generated by Django 5.2.3 on 2025-07-29 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0094_multiconsumer_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiconsumer',
            name='duplication',
            field=models.BooleanField(default=False),
        ),
    ]
