# Generated by Django 5.2.3 on 2025-07-29 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0095_multiconsumer_duplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaidGrouping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consumers.raidgroup')),
                ('raid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consumers.raid')),
            ],
        ),
    ]
