# Generated by Django 5.2.3 on 2025-07-29 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0096_raidgrouping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raidgroup',
            name='raids',
        ),
    ]
