# Generated by Django 5.2.3 on 2025-07-29 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0097_remove_raidgroup_raids'),
    ]

    operations = [
        migrations.AddField(
            model_name='raidgroup',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='raidgroup',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
