# Generated by Django 5.2.3 on 2025-07-29 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0098_raidgroup_description_alter_raidgroup_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='load_kw',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
