# Generated by Django 5.2.3 on 2025-07-30 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0099_consumer_load_kw'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumerGrouping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consumers.consumer')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consumers.consumergroup')),
            ],
        ),
    ]
