# Generated by Django 5.2.3 on 2025-07-30 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0100_consumergrouping'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumergrouping',
            name='remark',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
