# Generated by Django 5.2.3 on 2025-07-30 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0101_consumergrouping_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='raid',
            name='staffs_engaged',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consumers.staff'),
        ),
    ]
