# Generated by Django 5.2.3 on 2025-07-30 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0102_raid_staffs_engaged'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raid',
            name='staffs_engaged',
        ),
        migrations.AddField(
            model_name='raid',
            name='staffs_engaged',
            field=models.ManyToManyField(blank=True, to='consumers.staff'),
        ),
    ]
