# Generated by Django 5.2.3 on 2025-07-30 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0103_remove_raid_staffs_engaged_raid_staffs_engaged'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumerhistory',
            name='status',
            field=models.CharField(choices=[('--', '--'), ('OPEN', 'OPEN'), ('CLOSED', 'CLOSED')], default='--', max_length=20),
        ),
    ]
