# Generated by Django 5.2.3 on 2025-07-30 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0104_consumerhistory_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumeNA',
            fields=[
                ('consumer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('contacts', models.CharField(blank=True, max_length=50, null=True)),
                ('subdivision', models.CharField(blank=True, max_length=50, null=True)),
                ('remark', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
