# Generated by Django 5.2.3 on 2025-07-30 07:16

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0105_consumena'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumena',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
