# Generated by Django 5.2.3 on 2025-07-30 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0106_consumena_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumena',
            name='remark',
            field=models.TextField(blank=True),
        ),
    ]
