# Generated by Django 5.2.3 on 2025-07-30 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0107_alter_consumena_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumena',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consumena',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
