# Generated by Django 5.2.3 on 2025-07-30 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0108_consumena_info_alter_consumena_remark'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConsumeNA',
            new_name='ConsumerNA',
        ),
    ]
