# Generated by Django 5.2.3 on 2025-07-30 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0109_rename_consumena_consumerna'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumergroup',
            name='consumer',
        ),
    ]
