# Generated by Django 5.2.3 on 2025-07-30 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0110_remove_consumergroup_consumer'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumergroup',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
