# Generated by Django 5.2.3 on 2025-07-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0111_consumergroup_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumergroup',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
