# Generated by Django 5.2.3 on 2025-07-30 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0112_consumergroup_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumergroup',
            name='group_code',
            field=models.CharField(default='CODE', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consumergroup',
            name='group_name',
            field=models.CharField(max_length=50),
        ),
    ]
