# Generated by Django 5.2.3 on 2025-07-30 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0113_consumergroup_group_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='raid',
            old_name='is_closed',
            new_name='done',
        ),
        migrations.RenameField(
            model_name='raid',
            old_name='unauthorised',
            new_name='fishy',
        ),
        migrations.RemoveField(
            model_name='raid',
            name='image',
        ),
        migrations.RemoveField(
            model_name='raid',
            name='tags',
        ),
        migrations.AddField(
            model_name='raid',
            name='untraceable',
            field=models.BooleanField(default=False),
        ),
    ]
