# Generated by Django 5.2.3 on 2025-07-30 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0114_rename_is_closed_raid_done_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaidType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raid_type', models.CharField(max_length=16)),
            ],
        ),
    ]
