# Generated by Django 5.2.3 on 2025-07-30 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0115_raidtype'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RaidType',
            new_name='RaidObservation',
        ),
    ]
