# Generated by Django 5.2.3 on 2025-07-30 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0116_rename_raidtype_raidobservation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='raidobservation',
            old_name='raid_type',
            new_name='observation',
        ),
    ]
