# Generated by Django 5.2.3 on 2025-07-30 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0117_rename_raid_type_raidobservation_observation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raidobservation',
            name='observation',
            field=models.CharField(max_length=30),
        ),
    ]
