# Generated by Django 5.2.3 on 2025-07-30 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0118_alter_raidobservation_observation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='raid',
            old_name='observation',
            new_name='comment',
        ),
    ]
