# Generated by Django 5.2.3 on 2025-07-30 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0119_rename_observation_raid_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='raid',
            name='observations',
            field=models.ManyToManyField(blank=True, to='consumers.raidobservation'),
        ),
    ]
