# Generated by Django 5.2.3 on 2025-07-30 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0120_raid_observations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raid',
            name='theft',
        ),
    ]
