# Generated by Django 5.2.3 on 2025-07-30 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0121_remove_raid_theft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raid',
            name='ok',
        ),
    ]
