# Generated by Django 5.2.3 on 2025-07-31 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0122_remove_raid_ok'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumergroup',
            name='group_code',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
