# Generated by Django 5.2.3 on 2025-07-31 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0123_alter_consumergroup_group_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiconsumer',
            name='consumer_b',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumer_b', to='consumers.consumer'),
        ),
    ]
