# Generated by Django 5.2.3 on 2025-08-01 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0124_multiconsumer_consumer_b'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiconsumer',
            name='consumer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='consumers.consumer'),
        ),
    ]
