# Generated by Django 5.2.3 on 2025-08-01 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0125_alter_multiconsumer_consumer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multiconsumer',
            name='consumers',
        ),
    ]
