# Generated by Django 5.2.3 on 2025-08-01 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0126_remove_multiconsumer_consumers'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiconsumer',
            name='dup_is_b',
            field=models.BooleanField(default=False),
        ),
    ]
