# Generated by Django 5.2.3 on 2025-08-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0127_multiconsumer_dup_is_b'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiconsumer',
            name='revise_bill',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='multiconsumer',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='Different connections'),
        ),
    ]
