# Generated by Django 5.2.3 on 2025-08-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0128_multiconsumer_revise_bill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiconsumer',
            name='mark_both',
            field=models.BooleanField(default=False),
        ),
    ]
