# Generated by Django 5.2.3 on 2025-08-01 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0129_multiconsumer_mark_both'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiconsumer',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
