# Generated by Django 5.2.3 on 2025-08-03 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0130_multiconsumer_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('text', models.CharField(blank=True, max_length=50, null=True)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('decimal', models.FloatField(blank=True, null=True)),
                ('boolean', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
