# Generated by Django 5.2.3 on 2025-08-04 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0131_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='raid',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
