# Generated by Django 5.2.3 on 2025-08-04 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0132_raid_remark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='raidobservation',
            old_name='observation',
            new_name='text',
        ),
    ]
