# Generated by Django 5.2.3 on 2025-08-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0133_rename_observation_raidobservation_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='meter',
            name='meter_no',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
