# Generated by Django 5.2.3 on 2025-08-04 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0134_meter_meter_no'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Meter',
            new_name='DefectiveMeter',
        ),
    ]
