# Generated by Django 5.2.3 on 2025-08-04 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0135_rename_meter_defectivemeter'),
    ]

    operations = [
        migrations.AddField(
            model_name='defectivemeter',
            name='fetch',
            field=models.BooleanField(default=False),
        ),
    ]
