# Generated by Django 5.2.3 on 2025-08-04 17:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0136_defectivemeter_fetch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('text', models.CharField(max_length=200)),
                ('add_todo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DefectiveMeterProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defective_meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consumers.defectivemeter')),
                ('progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consumers.progress')),
            ],
        ),
        migrations.AddField(
            model_name='defectivemeter',
            name='progress',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='consumers.defectivemeterprogress'),
        ),
    ]
