# Generated by Django 5.2.3 on 2025-08-04 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0137_progress_defectivemeterprogress_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raid',
            name='unused',
        ),
    ]
