# Generated by Django 5.2.3 on 2025-08-04 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0138_remove_raid_unused'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raid',
            name='fishy',
        ),
        migrations.RemoveField(
            model_name='raid',
            name='underbilled',
        ),
        migrations.RemoveField(
            model_name='raid',
            name='untraceable',
        ),
    ]
