# Generated by Django 5.2.3 on 2025-08-04 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0139_remove_raid_fishy_remove_raid_underbilled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiconsumer',
            name='mark',
            field=models.BooleanField(default=False),
        ),
    ]
