# Generated by Django 5.2.3 on 2025-08-05 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0140_multiconsumer_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defectivemeterprogress',
            name='progress',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='consumers.progress'),
        ),
    ]
