# Generated by Django 5.2.3 on 2025-08-05 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0141_alter_defectivemeterprogress_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defectivemeter',
            name='progress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consumers.defectivemeterprogress'),
        ),
    ]
