# Generated by Django 5.2.3 on 2025-08-05 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0142_alter_defectivemeter_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defectivemeter',
            name='meter_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
