# Generated by Django 5.2.3 on 2025-08-06 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0143_alter_defectivemeter_meter_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='raidobservation',
            name='theft',
            field=models.BooleanField(default=False),
        ),
    ]
