# Generated by Django 5.2.3 on 2025-08-06 11:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0144_raidobservation_theft'),
    ]

    operations = [
        migrations.AddField(
            model_name='raidgroup',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
