# Generated by Django 5.2.3 on 2025-08-06 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0145_raidgroup_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='raid',
            name='raid_groupings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raid_groupings', to='consumers.raidgrouping'),
        ),
    ]
