# Generated by Django 5.2.3 on 2025-08-06 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0146_raid_raid_groupings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raid',
            name='raid_groupings',
        ),
    ]
