# Generated by Django 5.2.3 on 2025-08-06 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0147_remove_raid_raid_groupings'),
    ]

    operations = [
        migrations.AddField(
            model_name='raid',
            name='raid_groups',
            field=models.ManyToManyField(blank=True, related_name='raid_groups', through='consumers.RaidGrouping', to='consumers.raidgroup'),
        ),
    ]
