# Generated by Django 5.2.3 on 2025-08-06 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0148_raid_raid_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raid',
            name='cash_flows',
            field=models.ManyToManyField(blank=True, related_name='raid_cash_flows', to='consumers.cashflow'),
        ),
        migrations.CreateModel(
            name='RaidCashFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consumers.cashflow')),
                ('raid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='consumers.raid')),
            ],
        ),
    ]
