# Generated by Django 5.2.3 on 2025-08-07 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0149_alter_raid_cash_flows_raidcashflow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raid',
            name='cash_flows',
        ),
    ]
