# Generated by Django 5.2.3 on 2025-08-07 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0150_remove_raid_cash_flows'),
    ]

    operations = [
        migrations.AddField(
            model_name='raidgroup',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
