# Generated by Django 5.2.3 on 2025-08-08 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0151_raidgroup_selected'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consumerhistory',
            options={'ordering': ['-date']},
        ),
    ]
