# Generated by Django 5.2.3 on 2025-08-08 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0152_alter_consumerhistory_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoryWork',
        ),
    ]
