# Generated by Django 5.2.3 on 2025-08-08 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0153_delete_historywork'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefectiveMeterCashFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_flows', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consumers.cashflow')),
                ('defective_meter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='consumers.defectivemeter')),
            ],
        ),
    ]
