# Generated by Django 5.2.3 on 2025-08-08 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0154_defectivemetercashflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='raidgroup',
            name='freezed',
            field=models.BooleanField(default=False),
        ),
    ]
