# Generated by Django 5.2.3 on 2025-08-08 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0155_raidgroup_freezed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raidgrouping',
            name='raid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raidgroupings', to='consumers.raid'),
        ),
    ]
