# Generated by Django 5.2.3 on 2025-08-08 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0156_alter_raidgrouping_raid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raid',
            name='raid_groups',
            field=models.ManyToManyField(through='consumers.RaidGrouping', to='consumers.raidgroup'),
        ),
    ]
