# Generated by Django 5.2.3 on 2025-08-08 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0157_alter_raid_raid_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raid',
            name='penalty_paid',
        ),
    ]
