# Generated by Django 5.2.3 on 2025-08-08 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0158_remove_raid_penalty_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raid',
            name='done',
        ),
    ]
