# Generated by Django 5.2.3 on 2025-08-09 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0159_remove_raid_done'),
    ]

    operations = [
        migrations.RenameField(
            model_name='defectivemeter',
            old_name='new_meter',
            new_name='new_meter_no',
        ),
        migrations.AddField(
            model_name='defectivemeter',
            name='contact_nos',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
