# Generated by Django 5.2.3 on 2025-08-09 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0160_rename_new_meter_defectivemeter_new_meter_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='defectivemeter',
            name='custodyx',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
