# Generated by Django 5.2.3 on 2025-08-09 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0161_defectivemeter_custodyx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defectivemeter',
            name='custodyx',
        ),
    ]
