# Generated by Django 5.2.3 on 2025-08-09 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0162_remove_defectivemeter_custodyx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumerhistory',
            name='defaulter',
        ),
        migrations.RemoveField(
            model_name='consumerhistory',
            name='disconnected',
        ),
        migrations.RemoveField(
            model_name='consumerhistory',
            name='internal',
        ),
        migrations.RemoveField(
            model_name='consumerhistory',
            name='raid',
        ),
        migrations.RemoveField(
            model_name='consumerhistory',
            name='resolution',
        ),
        migrations.RemoveField(
            model_name='consumerhistory',
            name='status',
        ),
        migrations.RemoveField(
            model_name='consumerhistory',
            name='theft',
        ),
        migrations.RemoveField(
            model_name='consumerhistory',
            name='unused',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='add_todo',
        ),
    ]
