# Generated by Django 5.2.3 on 2025-08-09 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0163_remove_consumerhistory_defaulter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='progress',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
