# Generated by Django 5.2.3 on 2025-08-09 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0164_log_status_progress_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='awaiting',
        ),
    ]
