# Generated by Django 5.2.3 on 2025-08-09 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0165_remove_log_awaiting'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaidProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consumers.progress')),
                ('raid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raid_progress', to='consumers.raid')),
            ],
        ),
    ]
