# Generated by Django 5.2.3 on 2025-08-09 21:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0166_raidprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('subject', models.TextField()),
                ('info', models.TextField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('LOW', 'LOW'), ('MEDIUM', 'MEDIUM'), ('HIGH', 'HIGH')], default='LOW', max_length=20)),
                ('status', models.CharField(choices=[('DONE', 'DONE'), ('PENDING', 'PENDING'), ('ONGOING', 'ONGOING'), ('FAILED', 'FAILED')], default='PENDING', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='progress',
            name='status_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='progress',
            name='status',
            field=models.CharField(choices=[('DONE', 'DONE'), ('PENDING', 'PENDING'), ('ONGOING', 'ONGOING'), ('FAILED', 'FAILED'), ('--', '--')], default='--', max_length=50),
        ),
        migrations.CreateModel(
            name='WorkProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consumers.progress')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consumers.work2')),
            ],
        ),
    ]
