# Generated by Django 5.2.3 on 2025-08-09 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0167_work2_progress_status_text_alter_progress_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumerwork',
            name='work2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='consumers.work2'),
        ),
    ]
