# Generated by Django 5.2.3 on 2025-08-09 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0168_consumerwork_work2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumerwork',
            name='work',
        ),
    ]
