# Generated by Django 5.2.3 on 2025-08-09 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0169_remove_consumerwork_work'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consumerwork',
            old_name='work2',
            new_name='work',
        ),
    ]
