# Generated by Django 5.2.3 on 2025-08-09 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0170_rename_work2_consumerwork_work'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Work2',
            new_name='Work',
        ),
    ]
