# Generated by Django 5.2.3 on 2025-08-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0171_rename_work2_work'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defectivemeter',
            name='progress',
        ),
        migrations.AlterField(
            model_name='progress',
            name='status',
            field=models.CharField(choices=[('DONE', 'DONE'), ('PENDING', 'PENDING'), ('ONGOING', 'ONGOING'), ('FAILED', 'FAILED'), ('RESOLVED', 'RESOLVED'), ('POSTPONED', 'POSTPONED'), ('--', '--')], default='--', max_length=50),
        ),
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('DONE', 'DONE'), ('PENDING', 'PENDING'), ('ONGOING', 'ONGOING'), ('FAILED', 'FAILED'), ('RESOLVED', 'RESOLVED'), ('POSTPONED', 'POSTPONED'), ('--', '--')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='work',
            name='status',
            field=models.CharField(choices=[('DONE', 'DONE'), ('PENDING', 'PENDING'), ('ONGOING', 'ONGOING'), ('FAILED', 'FAILED'), ('RESOLVED', 'RESOLVED'), ('POSTPONED', 'POSTPONED'), ('--', '--')], default='PENDING', max_length=50),
        ),
    ]
