# Generated by Django 5.2.3 on 2025-08-10 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0172_remove_defectivemeter_progress_alter_progress_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='defectivemeter',
            old_name='postpaid',
            new_name='changed_to_postpaid',
        ),
        migrations.AddField(
            model_name='defectivemeter',
            name='progress',
            field=models.ManyToManyField(blank=True, through='consumers.DefectiveMeterProgress', to='consumers.progress'),
        ),
    ]
