# Generated by Django 5.2.3 on 2025-08-10 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0173_rename_postpaid_defectivemeter_changed_to_postpaid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defectivemeter',
            name='fetch',
        ),
    ]
