# Generated by Django 5.2.3 on 2025-08-10 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0174_remove_defectivemeter_fetch'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnmigratedMeter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_no', models.CharField(max_length=20)),
                ('connection_id', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('contacts', models.CharField(blank=True, max_length=50, null=True)),
                ('info', models.TextField()),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
