# Generated by Django 5.2.3 on 2025-08-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0175_unmigratedmeter'),
    ]

    operations = [
        migrations.AddField(
            model_name='unmigratedmeter',
            name='consumer_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unmigratedmeter',
            name='remark',
            field=models.TextField(blank=True),
        ),
    ]
