# Generated by Django 5.2.3 on 2025-08-10 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0176_unmigratedmeter_consumer_id_unmigratedmeter_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unmigratedmeter',
            name='info',
            field=models.TextField(blank=True),
        ),
    ]
