# Generated by Django 5.2.3 on 2025-08-10 14:24

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0177_alter_unmigratedmeter_info'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='unmigratedmeter',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('meter_no'), name='unique_lower_meter_no'),
        ),
    ]
