# Generated by Django 5.2.3 on 2025-08-11 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0178_unmigratedmeter_unique_lower_meter_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defectivemetercashflow',
            name='cash_flows',
        ),
        migrations.AlterField(
            model_name='consumerhistory',
            name='cash_flows',
            field=models.ManyToManyField(blank=True, related_name='history_cashflows', to='consumers.cashflow'),
        ),
        migrations.AlterField(
            model_name='loadsurvey',
            name='remark',
            field=models.TextField(blank=True),
        ),
    ]
