# Generated by Django 5.2.3 on 2025-08-11 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0179_remove_defectivemetercashflow_cash_flows_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadsurvey',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
