# Generated by Django 5.2.3 on 2025-08-11 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0180_alter_loadsurvey_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='defectivemetercashflow',
            name='cash_flows',
            field=models.ManyToManyField(to='consumers.cashflow'),
        ),
    ]
