# Generated by Django 5.2.3 on 2025-08-11 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0181_defectivemetercashflow_cash_flows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defectivemetercashflow',
            name='defective_meter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consumers.defectivemeter'),
        ),
    ]
