# Generated by Django 5.2.3 on 2025-08-11 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0182_alter_defectivemetercashflow_defective_meter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defectivemetercashflow',
            name='cash_flows',
        ),
    ]
