# Generated by Django 5.2.3 on 2025-08-11 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0183_remove_defectivemetercashflow_cash_flows'),
    ]

    operations = [
        migrations.AddField(
            model_name='defectivemetercashflow',
            name='cash_flows',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='consumers.cashflow'),
        ),
    ]
