# Generated by Django 5.2.3 on 2025-08-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0184_defectivemetercashflow_cash_flows'),
    ]

    operations = [
        migrations.AddField(
            model_name='unmigratedmeter',
            name='load_kw',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
