# Generated by Django 5.2.3 on 2025-08-11 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0185_unmigratedmeter_load_kw'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='industry',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
