# Generated by Django 5.2.3 on 2025-08-11 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0186_consumer_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='billing_class',
            field=models.CharField(blank=True, choices=[('HT', 'HT'), ('LT', 'LT')], max_length=50, null=True),
        ),
    ]
