# Generated by Django 5.2.3 on 2025-08-19 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0187_consumer_billing_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='raidgrouping',
            name='remark',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
